### ISSUE TITLE
Preparing slides for the "Westminster Enterprise Week"

### ISSUE THREAD

**Issue by mxochicale** [xfetus/pe#12]
> To help them get their ideas off the ground, the council has launched an annual Westminster Enterprise Week to connect young people in Westminster to the world-class enterprise opportunities on their doorstep. Taking place in November, the week is packed with guest speaker events, interactive workshops and collaborative challenges to inspire young people to think like an entrepreneur.   https://businesswestminster.com/employment-skills-2/inspiring-young-enterprise/
Key points for the workshop:
* Date: 10th November 2021
* In-person workshop
* Audience is in from an age group between 13-14

**Comment by tardaw** [comment]
Slide 6: 

Healthcare Professionals:

Here I think to list the profession below a photo, I think that the top middle picture is more AI so not really healthcare directly 😊 and the bottom right pic here is more Biomed application so maybe not the right picture?.

Some suggested names for Medical Professions..

**General Doctor and Surgeons

Nurses and Midwives

Social workers

Radiologists and Sonographers (use the top left pic and top right pic)

Physiotherapists** 

Slide 7:

Biomedical engineering – Bridge the technology and healthcare jobs together
Then here I think the top right picture hard to tell what happening and top le
<img width="301" alt="AI" src="https://user-images.githubusercontent.com/85352715/133993384-2e6e7982-0b3d-4755-87a8-ea709751f655.png">
ft… but others we can talk to, I think to remove the top middle picture and put this for AI as attached.
 
Slide 26: 

I think at the bottom of the Biomedical slide (slide 7) – highlight the subjects they can do so its ties up to this slide😊

**Comment by tardaw** [comment]
![image](https://user-images.githubusercontent.com/85352715/134137552-0fdb9489-3df5-4500-92ce-c69e8b1d2442.png)

![image](https://user-images.githubusercontent.com/85352715/134137575-a1451e1e-bab0-4fd6-a715-1fb639c18e91.png)

![image](https://user-images.githubusercontent.com/85352715/134137593-9cae3bf0-7691-482c-930e-ed0c6cf73a1c.png)

![image](https://user-images.githubusercontent.com/85352715/134137606-76d31ec9-1ae6-4fb3-b546-0915a3833ef9.png)

**Comment by mxochicale** [comment]
Few comments from Jojo:
* Convey the message that there are no such steps to have wrong career
* Add Tareen's career journey 
* Audience is 16 to 18 years old college students interested in health and social care,
* To have a bit of more interaction ,perhaps we might like to breakdown the slides to be 5mins explanation and 15 minutes activity 
* Highly which slides are for activities in the workshop
