### ISSUE TITLE
3D print model might be useful for blind mothers

### ISSUE THREAD

**Issue by mxochicale** [xfetus/pe#6]
~~Few examples of 3d printed fetus has been done but not quite sure about the time and cost if for example three sets of fetuses are required to be printed. That said, I will follow this up in this issue~~ just moved this one  to issue #14 and rename the issue title

**Comment by nomadtahir** [comment]
3D print model useful for blind mothers; By using 3D images from ultrasounds to create a model of the fetus, visually impaired mothers and fathers can actually handle and feel their unborn baby's face, which is obviously a very meaningful experience as they can't see the typical 2D ultrasound photographs.

https://www.youtube.com/watch?v=LaN779JT5PA&ab_channel=TahirCivan 

![3D_Printed_foetuse](https://user-images.githubusercontent.com/69795597/126226968-eb76ceb5-57bc-453e-9b2c-f7bcd785f66a.jpeg)

**Comment by mxochicale** [comment]
Thanks @nomadtahir for your comment and references. Would be nice to have references on how many visually impaired people can get the benefit of 3D printing models?
